-- ==========================================
-- SUPER DENTAL CLINIC - SCHEMA + DATA SCRIPT
-- Run this in your Supabase SQL Editor
-- ==========================================

-- 1. Create APPOINTMENTS Table
CREATE TABLE IF NOT EXISTS public.appointments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  patient_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  date DATE NOT NULL,
  time TEXT NOT NULL,
  treatment TEXT,
  status TEXT DEFAULT 'Scheduled',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Appt" ON public.appointments FOR SELECT USING (true);
CREATE POLICY "Public Insert Appt" ON public.appointments FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Appt" ON public.appointments FOR UPDATE USING (true);

-- 2. Create SETTINGS Table
CREATE TABLE IF NOT EXISTS public.settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  clinic_name TEXT,
  subtitle TEXT,
  primary_color TEXT,
  secondary_color TEXT,
  admin_user TEXT,
  admin_pass TEXT,
  about_text TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Settings" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Public Insert Settings" ON public.settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Settings" ON public.settings FOR UPDATE USING (true);

-- 3. Create STAFF_PROFILES Table
CREATE TABLE IF NOT EXISTS public.staff_profiles (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  role TEXT DEFAULT 'Staff',
  email TEXT,
  phone TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE POLICY "Allow public update staff" ON staff_profiles FOR UPDATE USING (true);
CREATE POLICY "Allow public insert staff" ON staff_profiles FOR INSERT WITH CHECK (true);

-- Insert Default Staff
INSERT INTO staff_profiles (name, role, email)
SELECT 'Dr. Admin', 'Doctor', 'admin@example.com'
WHERE NOT EXISTS (SELECT 1 FROM staff_profiles);

-- 6. (Optional) Insert Sample Appointments
-- Uncomment the lines below if you want dummy data to test with
/*
INSERT INTO appointments (patient_name, phone, date, time, status, treatment)
VALUES 
('John Doe', '9876543210', CURRENT_DATE, '10:00', 'Scheduled', 'Dental Cleaning'),
('Jane Smith', '9123456789', CURRENT_DATE + 1, '11:00', 'Confirmed', 'Consultation'),
('Rahul Gupta', '9988776655', CURRENT_DATE + 2, '16:00', 'Completed', 'Root Canal');
*/
