-- ==========================================
-- SUPER DENTAL CLINIC - SCHEMA + DATA SCRIPT
-- Run this in your Supabase SQL Editor
-- WARNING: This will reset tables!
-- ==========================================

DROP TABLE IF EXISTS public.appointments;
DROP TABLE IF EXISTS public.settings;

-- 1. Create APPOINTMENTS Table
CREATE TABLE IF NOT EXISTS public.appointments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT,
  place TEXT,
  mobile TEXT,
  appointment_date TEXT,
  appointment_time TEXT,
  reason TEXT,
  fee NUMERIC,
  status TEXT DEFAULT 'Scheduled',
  booking_date TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Appt" ON public.appointments FOR SELECT USING (true);
CREATE POLICY "Public Insert Appt" ON public.appointments FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Appt" ON public.appointments FOR UPDATE USING (true);

-- 2. Create SETTINGS Table
CREATE TABLE IF NOT EXISTS public.settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  clinic_name TEXT,
  subtitle TEXT,
  primary_color TEXT,
  secondary_color TEXT,
  admin_user TEXT,
  admin_pass TEXT,
  about_text TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Settings" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Public Insert Settings" ON public.settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Settings" ON public.settings FOR UPDATE USING (true);

-- ==========================================
-- INSERT DATA
-- ==========================================

-- Settings Data
INSERT INTO public.settings (clinic_name, subtitle, primary_color, secondary_color, admin_user, admin_pass, about_text)
SELECT 'My Dental Clinic', 'Premium Dental Services', '#26A69A', '#42A5F5', 'admin@example.com', 'admin123', 'Welcome to our premium dental facility. We provide top-notch care using the latest digital technology.'
WHERE NOT EXISTS (SELECT 1 FROM public.settings);

-- Appointment Data (Sample)
INSERT INTO public.appointments (name, place, mobile, appointment_date, appointment_time, reason, status, booking_date, fee)
VALUES 
('John Doe', 'Dahod', '9876543210', '2026-01-30', '10:00', 'Dental Cleaning', 'Scheduled', '2026-01-24', 500),
('Jane Smith', 'Godhra', '9123456789', '2026-02-01', '11:00', 'Consultation', 'Confirmed', '2026-01-24', 200),
('Rahul Gupta', 'Dahod', '9988776655', '2026-02-02', '16:00', 'Root Canal', 'Completed', '2026-01-24', 1500);
